---
# -- [ec2]
# -- local ansible_connection=local
ec2:
  hosts:
    postgresserver:
      ansible_host: 18.224.140.246
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
