---
# -- [ec2]
# -- local ansible_connection=local
ec2:
  hosts:
    postgresserver:
      ansible_host: 54.144.225.28
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/.ssh/id_rsa.pem
      ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
