- name: Update all packages
  yum:
    name: "*"
    state: latest
    update_only: yes

- name: Ensure a list of yum packages are installed
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - python-pip
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - amazon-linux-extras

- name: Add extras repository
  shell: yum-config-manager --enable extras

- name: Enable Some packages from amazon-linux-extras packages
  shell: "amazon-linux-extras enable python3.8 ansible2 docker"
  #  https://www.linkedin.com/pulse/docker-aws-amazon-linux-2-instance-steven-aranibar/
  # That blog explain an error of dependencies when trying to install docker mannually.

- name: Clean yum metadata cache
  command: yum clean metadata

- name: Ensure a list of yum packages are installed
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - python3.8
      - ansible
      - docker

- name: Enable Docker CE service at startup
  service:
    name: docker
    state: started
    enabled: yes

- name: Upgrade pip3
  shell: "python3.8 -m pip install pip --upgrade"

- name: Ensure Python pip packages are installed
  pip:
    name: "{{ packages }}"
    executable: /usr/local/bin/pip3.8
  vars:
    packages:
      - boto
      - boto3
      - docker-compose

- name: Add the ec2-user user to the Docker group
  user:
    name: "ec2-user"
    group: docker
