CREATE TABLE global.Clientes (
	idCliente int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	Nombre VARCHAR2(50) NOT NULL,
	Apellido VARCHAR2(20) NOT NULL,
	Correo VARCHAR2(50) NOT NULL UNIQUE,
	constraint CLIENTES_PK PRIMARY KEY (idCliente));

CREATE TABLE global.Lugares (
	idLugar int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	Nombre VARCHAR2(50) NOT NULL,
	Direccion VARCHAR2(300) NOT NULL,
	constraint LUGARES_PK PRIMARY KEY (idLugar));

CREATE TABLE global.Cajeros (
	idCajero int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	Nombre VARCHAR2(50) NOT NULL,
	Banco VARCHAR2(50) NOT NULL,
    Lugar INT NOT NULL,
	constraint CAJEROS_PK PRIMARY KEY (idCajero));

CREATE TABLE global.Comprobantes (
	idComprobante int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	Monto FLOAT NOT NULL,
	Cajero INT NOT NULL,
    Cliente INT NOT NULL,
    Fecha DATE NOT NULL,
    Producto INT NOT NULL,
	constraint COMPROBANTES_PK PRIMARY KEY (idComprobante));

CREATE TABLE global.Productos (
	idProducto int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	Nombre VARCHAR2(50) NOT NULL,
	Descripcion VARCHAR2(150) NOT NULL,
	constraint PRODUCTOS_PK PRIMARY KEY (idProducto));

ALTER TABLE Cajeros ADD CONSTRAINT Lugar_fk0 FOREIGN KEY (Lugar) REFERENCES Lugares(idLugar);
ALTER TABLE Comprobantes ADD CONSTRAINT Cajero_fk0 FOREIGN KEY (Cajero) REFERENCES Cajeros(idCajero);
ALTER TABLE Comprobantes ADD CONSTRAINT Cliente_fk0 FOREIGN KEY (Cliente) REFERENCES Clientes(idCliente);
ALTER TABLE Comprobantes ADD CONSTRAINT Producto_fk0 FOREIGN KEY (Producto) REFERENCES Productos(idProducto);

CREATE sequence Clientes_IDCliente_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOORDER  
  NOCYCLE
  CACHE 20;

CREATE sequence Lugares_IDLugar_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOORDER  
  NOCYCLE
  CACHE 20;

CREATE sequence Cajeros_IDCajero_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOORDER  
  NOCYCLE
  CACHE 20;

CREATE sequence Comprobantes_IDComprobante_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOORDER  
  NOCYCLE
  CACHE 20;

CREATE sequence Productos_IDProducto_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOORDER  
  NOCYCLE
  CACHE 20;

CREATE OR REPLACE trigger BI_Clientes_IDCliente
before insert on global.Clientes
for each row
begin
select Clientes_IDCliente_SEQ.nextval into :NEW.idCliente from dual;
end;
/

CREATE OR REPLACE trigger BI_Lugares_IDLugar
before insert on global.Lugares
for each row
begin
select Lugares_IDLugar_SEQ.nextval into :NEW.idLugar from dual;
end;
/

CREATE OR REPLACE trigger BI_Cajeros_IDCajero
before insert on global.Cajeros
for each row
begin
select Cajeros_IDCajero_SEQ.nextval into :NEW.idCajero from dual;
end;
/

CREATE OR REPLACE trigger BI_Comprobantes_IDComprobante
before insert on global.Comprobantes
for each row
begin
select Comprobantes_IDComprobante_SEQ.nextval into :NEW.idComprobante from dual;
end;
/

CREATE OR REPLACE trigger BI_Productos_IDProducto
before insert on global.Productos
for each row
begin
select Productos_IDProducto_SEQ.nextval into :NEW.idProducto from dual;
end;
/

-- DROP TABLE global.Clientes CASCADE CONSTRAINTS;
-- DROP TABLE global.Lugares CASCADE CONSTRAINTS;
-- DROP TABLE global.Cajeros CASCADE CONSTRAINTS;
-- DROP TABLE global.Productos CASCADE CONSTRAINTS;
-- DROP TABLE global.Comprobantes CASCADE CONSTRAINTS;
-- DROP sequence Clientes_IDCliente_SEQ;
-- DROP sequence Lugares_IDLugar_SEQ;
-- DROP sequence Cajeros_IDCajero_SEQ;
-- DROP sequence Comprobantes_IDComprobante_SEQ;
-- DROP sequence Productos_IDProducto_SEQ;