CREATE TABLE MODELO(
ID_MODULO SERIAL PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL, 
DESCRIPCION VARCHAR(200) NOT NULL,
DIMENSIONES VARCHAR(50)NOT NULL,
IMG BYTEA NOT NULL
);

CREATE TABLE CONTACTO(
ID_CONTACTO SERIAL PRIMARY KEY,
ID_MODULO INT NOT NULL,
NUMERO INT NOT NULL, 
EMAIL VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(200) NOT NULL,
IMG BYTEA, 
CONSTRAINT fk_MODELO
   FOREIGN KEY(ID_MODULO)
   REFERENCES MODELO(ID_MODULO)
);

CREATE TABLE USUARIO(
ID_USUARIO SERIAL PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL, 
APELLIDO VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
NUMERO INT NOT NULL, 
DOMICILIO VARCHAR(200) NOT NULL,
TIPO_USUARIO BOOL NOT NULL,
IMG BYTEA
);

CREATE TABLE PROVEEDOR(
ID_PROVEEDOR SERIAL PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL, 
APELLIDO VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
NUMERO INT NOT NULL, 
DIRECCION VARCHAR(200) NOT NULL
);

CREATE TABLE PRODUCTO(
ID_PRODUCTO SERIAL PRIMARY KEY,
ID_PROVEEDOR INT NOT NULL,
CANTIDAD INT NOT NULL, 
PRECIO DECIMAL NOT NULL,
NUMERO INT NOT NULL, 
DESCRIPCION VARCHAR(200) NOT NULL, 
CONSTRAINT fk_MODELO
   FOREIGN KEY(ID_PROVEEDOR) 
   REFERENCES PROVEEDOR(ID_PROVEEDOR)
);

-- DROP TABLE MODELO CASCADE;
-- DROP TABLE CONTACTO CASCADE;
-- DROP TABLE USUARIO;
-- DROP TABLE PROVEEDOR;
-- DROP TABLE PRODUCTO;
